service:
  name: linkal

custom:
  environment:
    serviceName: ${self:service.name}
  prune:
    automatic: true
    includeLayers: true
    number: 5
  webpack:
    webpackConfig: ${opt:debug, 'webpack.config.js'}
    includeModules: true

package:
  individually: true

plugins:
  - serverless-offline
  - serverless-prune-plugin
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  versionFunctions: false
  logs:
    restApi: true
  logRetentionInDays: 180
  tracing:
    apiGateway: true
    lambda: true
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1 # reuse HTTP connections : https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-reusing-connections.html

functions:
  hello:
    name: ${self:service.name}-hello
    description: 'API Gateway: Hello world message'
    handler: src/routes/hello-world/index.handler
    environment: ${self:custom.environment}
    events:
      - http:
          method: post
          path: /hello
          request:
            schema:
              application/json: ${file(src/routes/hello-world/schema.json)}
